# Generated by Django 4.2.5 on 2023-09-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Slider', 'Slider'), ('Home/About', 'Home/About'), ('Normal', 'Normal'), ('Home/Gallery', 'Home/Gallery'), ('Program', 'Program'), ('Program_1', 'Program_1'), ('About', 'About'), ('Why', 'Why'), ('Why_1', 'Why_1'), ('Why_2', 'Why_2'), ('Why_3', 'Why_3'), ('Why_4', 'Why_4'), ('Why_5', 'Why_5'), ('Why_6', 'Why_6'), ('Why_7', 'Why_7'), ('Testimonials', 'Testimonials'), ('Testimonials_1', 'Testimonials_1'), ('Why_8', 'Why_8'), ('Why_9', 'Why_9'), ('Why_10', 'Why_10'), ('Why_11', 'Why_11'), ('Why_12', 'Why_12'), ('Why_13', 'Why_13'), ('Why_14', 'Why_14'), ('Why_15', 'Why_15'), ('Why_16', 'Why_16'), ('Why_17', 'Why_17'), ('About_1', 'About_1'), ('About_2', 'About_2'), ('About_3', 'About_3'), ('Science', 'Science'), ('Management', 'Management'), ('Humanities', 'Humanities'), ('BBS', 'BBS'), ('BBA', 'BBA'), ('Bsc.CSIT', 'Bsc.CSIT'), ('+2 Program', '+2 Program'), ('Bachelors Program', 'Bachelors Program'), ('SubjectTitle', 'SubjectTitle'), ('SubjectTitle_1', 'SubjectTitle_1'), ('Science_1', 'Science_1'), ('Management_1', 'Management_1'), ('Humanities_1', 'Humanities_1'), ('BBS_1', 'BBS_1'), ('BBA_1', 'BBA_1'), ('Bsc.CSIT_1', 'Bsc.CSIT_1'), ('Gallery', 'Gallery'), ('Gallery_1', 'Gallery_1'), ('Video', 'Video'), ('Video_1', 'Video_1'), ('Contact', 'Contact'), ('New/Event', 'New/Event'), ('New/Event_1', 'New/Event_1'), ('Admission', 'Admission'), ('Popup', 'Popup')], max_length=50, null=True),
        ),
    ]
